Add port ranges
containers/netavark pull request #138
Opened 2021-12-20 18:32 UTC by baude

Use the ability of ranges with iptables instead of creating multiple
rules for each port.

Signed-off-by: Brent Baude <bbaude@redhat.com>

2021-12-20 20:09 UTC, Luap99 reviewed
The tests are failing, it looks like always the second ncat fails with connection refused.

2021-12-20 20:09 UTC, Luap99 commented on test/100-bridge-iptables.bats
> -@test "$fw_driver - internal network" {
Why is this removed?

2021-12-20 20:09 UTC, Luap99 commented on test/100-bridge-iptables.bats
> +    test_port_fwrange=3
```suggestion
    test_port_fw range=3
```

2021-12-20 20:09 UTC, Luap99 commented on test/100-bridge-iptables.bats
> +}
Can you also add a test with ip=dual

2021-12-21 15:34 UTC, flouthoc commented on test/100-bridge-iptables.bats
> +    test_port_fwrange=3
@baude This is not yet fixed

2021-12-21 20:03 UTC, flouthoc commented
@baude I think there is something up with the code. Cause the example you were trying with `-p 8080-8082:80-82` works with `main` branch without this PR. So podman is for sure splitting port forward into seperate entries rather than using `range` field.

I wonder if we only need this PR for `-p 8080-8082:80-82` then it works with `firewall` disabled from the current `main` without any addition.

For `range` part i think there is something up with the code cause tests looked fine to me.

2021-12-21 20:25 UTC, Luap99 commented
@flouthoc You can run with `--log-level trace`, this will show you the exact config for netavark. I am pretty sure `-p 8080-8082:80-82` creates a range, if not than this is a bug

2021-12-21 20:46 UTC, flouthoc commented
@Luap99 I'll try that but could you also confirm if this works for you from `main` branch. `run -it -p 8080:8082:80-82 quay.io/libpod/alpine_nginx` and make sure you switch the backend to `netavark`.

2021-12-21 21:13 UTC, Luap99 commented
I am on PTO. I have no access to my workstation so I cannot test netavark

2021-12-22 06:50 UTC, flouthoc requested changes
@baude There is a tiny logical error or typo in `DNAT` rule `--dport` must accept `host-range`. Following diff should make it work and CI should also pass.

Could you please amend PR with following diff.

```diff
diff --git a/src/firewall/varktables/types.rs b/src/firewall/varktables/types.rs
index 05df4e1..c6884ae 100644
--- a/src/firewall/varktables/types.rs
+++ b/src/firewall/varktables/types.rs
@@ -418,7 +418,7 @@ pub fn get_port_forwarding_chains<'a>(
                 i.protocol,
                 container_ip_value,
                 container_port,
-                i.host_port.to_string(),
+                &host_port
             ),
             None,
         ));
```

2021-12-22 11:47 UTC, flouthoc commented
@baude cargo fmt is needed.

2021-12-22 12:10 UTC, flouthoc approved these changes

2021-12-22 12:18 UTC, flouthoc commented
/lgtm

2021-12-22 12:18 UTC, merged

2021-12-23 09:07 UTC, Luap99 commented
Please restore the internal test and add the ip=dual case as noted in the review e ts