Fix typos
containers/netavark pull request #594
Opened 2023-02-21 03:21 UTC by kianmeng

Found via `typos --format brief`

2023-02-21 20:54 UTC, edsantiago requested changes
Thank you @kianmeng !

Changes LGTM with one exception. And, you need to [sign your commits](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs).

2023-02-21 20:54 UTC, edsantiago commented on src/network/core_utils.rs
> +    // make sure autoconf is off, we want manually config only
This should actually be `manual`, not manually.

2023-02-22 03:45 UTC, baude commented
/hold
/lgtm

2023-02-22 13:39 UTC, edsantiago approved these changes
/hold cancel

Thank you!

2023-02-22 13:44 UTC, merged

2023-02-23 03:21 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: