macvlan: add bclim option
containers/netavark pull request #698
Opened 2023-05-24 14:40 UTC by Luap99

Expose the netlink IFLA_MACVLAN_BC_CUTOFF option as bclim like the ip
command does. We still need c/common and podman patches to allow this
option for podman network create.

Also I created a PR[1] upstream in the netlink lib to allow setting
these options directly instead of using the DefaultNla work around as I
do here.

TODO: Add a test but for now this option is not in a released version of
iproute so there is no way to check for it right now.

[1] https://github.com/rust-netlink/netlink-packet-route/pull/32

This is needed for https://bugzilla.redhat.com/show_bug.cgi?id=2183896

2023-05-24 14:43 UTC, Luap99 commented
@mheon @flouthoc PTAL

Fortunately netlink upstream changes are not required for this feature so I implemented it like this for now. That should help back porting. I tested it on RHEL at it seemed to work correctly.

2023-05-24 14:54 UTC, mheon commented
LGTM

2023-05-24 15:29 UTC, flouthoc requested changes
Needs `fmt`

```diff
diff --git a/src/network/bridge.rs b/src/network/bridge.rs
index 88fbf23..20afed0 100644
--- a/src/network/bridge.rs
+++ b/src/network/bridge.rs
@@ -75,7 +75,8 @@ impl driver::NetworkDriver for Bridge<'_> {
         let ipam = get_ipam_addresses(self.info.per_network_opts, self.info.network)?;
 
         let mtu: u32 = parse_option(&self.info.network.options, OPTION_MTU)?.unwrap_or(0);
-        let isolate: bool = parse_option(&self.info.network.options, OPTION_ISOLATE)?.unwrap_or(false);
+        let isolate: bool =
+            parse_option(&self.info.network.options, OPTION_ISOLATE)?.unwrap_or(false);
         let metric: u32 = parse_option(&self.info.network.options, OPTION_METRIC)?.unwrap_or(100);
         let no_default_route: bool =
             parse_option(&self.info.network.options, OPTION_NO_DEFAULT_ROUTE)?.unwrap_or(false);
@@ -389,8 +390,7 @@ impl<'a> Bridge<'a> {
             Some(d) => (&d.ipam.container_addresses, &d.ipam.nameservers, d.isolate),
             None => {
                 // options are not yet parsed
-                let isolate:bool = match parse_option(&self.info.network.options, OPTION_ISOLATE)
-                {
+                let isolate: bool = match parse_option(&self.info.network.options, OPTION_ISOLATE) {
                     Ok(i) => i.unwrap_or(false),
                     Err(e) => {
                         // just log we still try to do as much as possible for cleanup
```

2023-05-25 10:29 UTC, Luap99 commented
@flouthoc PTAL again

2023-05-25 15:10 UTC, flouthoc approved these changes
LGTM

2023-05-25 15:10 UTC, merged