Use tonic::transport::Uri instead of HTTP
containers/netavark pull request #873
Opened 2023-12-14 13:16 UTC by baude

With http-1.0.0, the use of HTTP::Uri is no longer valid for when a tonic::transport::Uri is required.

2023-12-14 13:27 UTC, baude commented
this replaces #847

2023-12-14 13:33 UTC, Luap99 requested changes
This works but you just dropped the only import were http was used so the better solution just drop http as dependency and let our direct dependencies such as tonic handle the version of http they are using.

2023-12-14 14:10 UTC, Luap99 approved these changes
LGTM

2023-12-15 16:10 UTC, Luap99 commented
/lgtm

2023-12-15 16:13 UTC, merged